name: apple_music_api
description: Apple music api pluggin for flutter.
version: 0.0.1
author: Amirala Masoomi
homepage: https://proper.zone

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  flutter_sound: ^8.1.1
  intl: ^0.17.0
  just_audio: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
